name: Publish
on:
  workflow_call:

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to DockerHub
        uses: docker/build-push-action@v4
        with:
          build-args: NG_CONFIGURATION=production
          push: true
          context: .
          tags: "ghcr.io/audiowalk-cz/audiowalk-korzo-2024:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
